routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('guest')->group(function(){

    Route::name('index')->get('/', 'LoginController@index');
    Route::name('login')->get('/', 'LoginController@index');
    Route::name('login.post')->post('/login/post', 'LoginController@login');

});

Route::middleware('auth')->group(function(){

    Route::middleware('admin')->group(function(){

        Route::name('dashboard')->get('dashboard', 'DashboardController@index');
        Route::name('home')->get('home', 'DashboardController@index');
        Route::name('activity')->get('activity', 'ActivityController@index');
        Route::name('logout')->get('logout', 'LoginController@logout');
    
        Route::resources([
            'product' => 'ProductController',
            'video' => 'VideoController', //add
            'order' => 'OrderController',
            'category' => 'CategoryController',
            'subcategory' => 'SubCategoryController',
            'user' => 'UserController',
            'role' => 'RoleController',
            'login_history' => 'LoginHistoryController',
        ]);
    
        Route::name('setting.')->prefix('setting')->group(function(){
    
            Route::name('index')->get('/','SettingController@index');
            Route::name('basic')->post('basic','SettingController@basic');
            Route::name('social')->post('social','SettingController@social');
            Route::name('payment')->post('payment','SettingController@payment');
            Route::name('icon')->post('icon','SettingController@icon');
            Route::name('slider')->post('slider','SettingController@slider');
    
        });
    
        Route::name('ajax.')->prefix('ajax')->group(function(){
            
            Route::name('delete_slider')->get('delete_slider/{id}', 'AjaxController@delete_slider');    
            Route::name('delete_photo')->get('delete_photo/{id}', 'AjaxController@delete_photo');    
            
        });
    
    });

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function images()
    {
        return $this->hasMany('App\Models\ProductImage', 'product_id');
    }

    public function category()
    {
        return $this->belongsTo('App\Models\Category', 'category_id');
    }

    public function subcategory()
    {
        return $this->belongsTo('App\Models\SubCategory', 'subcategory_id');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ProductRequest;
use App\Models\Product;
use App\Models\ProductImage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::whereDeleted(0)
        ->latest()
        ->get();

        return view('dashboard.pages.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.pages.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {

        $code = str_random(6);

        $product = new Product;
        $product->code = $code;
        $product->name = $request->name;
        $product->sku = $request->sku;
        $product->category_id = $request->category_id;
        $product->subcategory_id = $request->subcategory_id;
        $product->price = $request->price;
        $product->desc = $request->desc;
        $product->tags = $request->tags;
        $product->status = $request->status;
        $product->save();

        $path = createDirectory("storage/products", $code);

        foreach($request->image as $index => $image) {
            $product_image = new ProductImage;
            $product_image->product_id = $product->id;
            $product_image->image = storeFile($path, str_random(3), $request->file('image')[$index]);
            $product_image->save();
        }

        addActivity("create", "Product: " . $product->name);
        session()->flash('success', "Product has been created");
        return redirect()->route('product.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        return view('dashboard.pages.product.update', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $product->name = $request->name;
        $product->sku = $request->sku;
        $product->category_id = $request->category_id;
        $product->subcategory_id = $request->subcategory_id;
        $product->price = $request->price;
        $product->desc = $request->desc;
        $product->tags = $request->tags;
        $product->status = $request->status;
        $product->save();

        if($request->hasFile('image')) {
            $path = createDirectory("storage/products", $product->code);

            foreach($request->image as $index => $image) {
                $product_image = new ProductImage;
                $product_image->product_id = $product->id;
                $product_image->image = storeFile($path, str_random(3), $request->file('image')[$index]);
                $product_image->save();
            }
        }

        addActivity("update", "Product: " . $product->name);
        session()->flash('success', "Product has been updated");
        return redirect()->route('product.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        foreach($product->images as $image){
            $path = getStoragePath($image->image);
            deleteFile($path);
            $image->delete();
        }

        $product->status = false;
        $product->deleted = true;
        $product->update();

        addActivity("delete", "Product: " . $product->name);
        return response()->json([
            'status' => 200
        ]);

    }
}

resources/views/dashboard/pages/product/create.blade.php
@component('dashboard.layouts.app')
    @slot('title')
        Create Product
    @endslot
    @slot('custom_css')
        <link rel="stylesheet" href="{{ asset('css/dropify.min.css') }}">
    @endslot
    @slot('content')
        <div class="page-header card">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <i class="fas fa-tags bg-c-blue"></i>
                        <div class="d-inline">
                            <h5>Create Product</h5>
                            <span>New Product</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="page-header-breadcrumb">
                        <ul class=" breadcrumb breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="{{ route('dashboard') }}">Dashboard</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('product.index') }}">All Products</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">New Product</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="pcoded-inner-content">
            <div class="main-body">
                <div class="page-wrapper">
                    <div class="page-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>Create Form</h5>
                                    </div>
                                    <div class="card-block">
                                        <form method="post" id="form" action="{{ route('product.store') }}" enctype="multipart/form-data">
                                            @csrf
                                            <div class="form-row">
                                                <div class="form-group col-md-6">
                                                    <label for="name">Name <span class="required">*</span></label>
                                                    <input type="text" id="name" name="name" placeholder="Enter Name" value="{{ old('name') }}" class="form-control @if($errors->has('name')) is-invalid @endif">
                                                    @if($errors->has('name'))<div class="invalid-feedback">{{ $errors->first('name') }}</div>@endif
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="sku">SKU</label>
                                                    <input type="text" id="sku" name="sku" placeholder="Enter SKU Number" value="{{ old('sku') }}" class="form-control @if($errors->has('sku')) is-invalid @endif">
                                                    @if($errors->has('sku'))<div class="invalid-feedback">{{ $errors->first('sku') }}</div>@endif
                                                </div>
                                            </div>
                                            <div class="form-row">
                                                <div class="form-group col-md-6">
                                                    <label for="category_id">Category <span class="required">*</span></label>
                                                    <select name="category_id" id="category_id" class="form-control @if($errors->has('category_id')) is-invalid @endif">
                                                        <option value="">Select Category</option>
                                                        @foreach(getCategories() as $category)
                                                            @if(old('category_id') == $category->id)
                                                                <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
                                                            @else
                                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                            @endif
                                                        @endforeach
                                                    </select>
                                                    @if($errors->has('category_id'))<div class="invalid-feedback">{{ $errors->first('category_id') }}</div>@endif
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="subcategory_id">Sub Category</label>
                                                    <select name="subcategory_id" id="subcategory_id" class="form-control @if($errors->has('subcategory_id')) is-invalid @endif">
                                                        <option value="">Select Sub Category</option>
                                                        @foreach(getSubCategories() as $category)
                                                            @if(old('subcategory_id') == $category->id)
                                                                <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
                                                            @else
                                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                            @endif
                                                        @endforeach
                                                    </select>
                                                    @if($errors->has('subcategory_id'))<div class="invalid-feedback">{{ $errors->first('subcategory_id') }}</div>@endif
                                                </div>
                                            </div>
                                            <div class="form-row">
                                                <div class="form-group col-md-4">
                                                    <label for="price">Price <span class="required">*</span></label>
                                                    <input type="number" id="price" name="price" step="0.01" placeholder="Enter Price" value="{{ old('price') }}" class="form-control @if($errors->has('price')) is-invalid @endif">
                                                    @if($errors->has('price'))<div class="invalid-feedback">{{ $errors->first('price') }}</div>@endif
                                                </div>
                                                <div class="form-group col-md-4">
                                                    <label for="tags">Tags </label>
                                                    <input type="text" id="tags" name="tags" placeholder="Enter Tags" value="{{ old('tags') }}" class="form-control @if($errors->has('tags')) is-invalid @endif">
                                                    @if($errors->has('tags'))<div class="invalid-feedback">{{ $errors->first('tags') }}</div>@endif
                                                </div>
                                                <div class="form-group col-md-4">
                                                    <label for="desc">Description</label>
                                                    <textarea name="desc" id="desc" rows="5" placeholder="Enter Description" class="form-control @if($errors->has('subcategory_id')) is-invalid @endif"></textarea>
                                                    @if($errors->has('desc'))<div class="invalid-feedback">{{ $errors->first('desc') }}</div>@endif
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="image">Photos/Images <span class="required">*</span></label>
                                                <input type="file" name="image[]" id="image" class="dropify" multiple="true" data-allowed-file-extensions="jpg jpeg png" data-errors-position="outside" data-show-errors="true">
                                                @if($errors->has('image'))<div class="invalid-feedback">{{ $errors->first('image') }}</div>@endif
                                            </div>
                                            <div class="form-group">
                                                <label for="status">Status <span class="required">*</span></label>
                                                <select name="status" id="status" class="form-control">
                                                    <option value="1">Active</option>
                                                    <option value="0">Inactive</option>
                                                </select>
                                                @if($errors->has('status'))<div class="invalid-feedback">{{ $errors->first('status') }}</div>@endif
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer">
                                        <a href="{{ route('product.index') }}" class="btn btn-light">Back</a>
                                        <input type="submit" form="form" value="Submit" class="btn btn-primary">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endslot
    @slot('custom_js')
    <script src="{{ asset('js/dropify.min.js')}}"></script>
    <script>
        $('.dropify').dropify();
    </script>
    @endslot
@endcomponent

resources/views/dashboard/pages/product/index.blade.php
@component('dashboard.layouts.app')
@slot('title')
Manage All Products
@endslot
@slot('custom_css')
<link rel="stylesheet" href="{{ asset('css/datatables.min.css') }}">
@endslot
@slot('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="fas fa-tags bg-c-blue"></i>
                <div class="d-inline">
                    <h5>Products</h5>
                    <span>Manage All Products</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class=" breadcrumb breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('dashboard') }}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#">All Products</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Products List</h5>
                                <a href="{{ route('product.create') }}" class="btn btn-sm btn-primary float-right">
                                    <i class="fa fa-plus"></i>
                                    Product
                                </a>
                            </div>
                            <div class="card-block">
                                <div class="dt-responsive table-responsive">
                                    <table id="dataTable" class="table table-hover table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="text-center">#</th>
                                                <th></th>
                                                <th>Name</th>
                                                <th>SKU</th>
                                                <th>Category</th>
                                                <th>Sub Category</th>
                                                <th class="text-right">Price</th>
                                                <th class="text-center">Status</th>
                                                <th class="text-right">Date</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($products as $product)
                                            <tr>
                                                <td align="center">{{ $loop->iteration }}</td>
                                                <td>
                                                    <img src="{{ url($product->images[0]->image) }}" alt="" width="100%">
                                                </td>
                                                <td>{{ $product->name }}</td>
                                                <td>{{ $product->sku }}</td>
                                                <td>{{ $product->category->name }}</td>
                                                <td>{{ $product->subcategory == null ? 'N/A' : $product->subcategory->name }}</td>
                                                <td align="right">{{ $product->price }}</td>
                                                <td align="center">
                                                    <label class="label {{ $product->status == 1 ? 'label-success' : 'label-danger' }}">
                                                        {{ $product->status == 1 ? 'Active' : 'Inactive' }}
                                                    </label>
                                                </td>
                                                <td align="right">{{ getDefaultDate($product->created_at) }}</td>
                                                <td align="right">
                                                    <a href="{{ route('product.edit', $product) }}" class="btn btn-mini btn-warning">
                                                        <i class="fa fa-pencil-alt"></i>
                                                    </a>
                                                    <a href="" id="btnDelete" data-id="{{ $product->id }}" data-func="product" class="btn btn-mini btn-danger">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="text-center">#</th>
                                                <th></th>
                                                <th>Name</th>
                                                <th>SKU</th>
                                                <th>Category</th>
                                                <th>Sub Category</th>
                                                <th class="text-right">Price</th>
                                                <th class="text-center">Status</th>
                                                <th class="text-right">Date</th>
                                                <th></th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endslot
@slot('custom_js')
<script src="{{ asset('js/function.js?id=' . str_random(5)) }}"></script>
<script src="{{ asset('js/datatables.min.js?id=' . str_random(5)) }}"></script>
<script>
    $('#dataTable').DataTable({});
</script>
@endslot
@endcomponent