routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('guest')->group(function(){

    Route::name('index')->get('/', 'LoginController@index');
    Route::name('login')->get('/', 'LoginController@index');
    Route::name('login.post')->post('/login/post', 'LoginController@login');

});

Route::middleware('auth')->group(function(){

    Route::middleware('admin')->group(function(){

        Route::name('dashboard')->get('dashboard', 'DashboardController@index');
        Route::name('home')->get('home', 'DashboardController@index');
        Route::name('activity')->get('activity', 'ActivityController@index');
        Route::name('logout')->get('logout', 'LoginController@logout');
    
        Route::resources([
            'product' => 'ProductController',
            'video' => 'VideoController', //add
            'order' => 'OrderController',
            'category' => 'CategoryController',
            'subcategory' => 'SubCategoryController',
            'user' => 'UserController',
            'role' => 'RoleController',
            'login_history' => 'LoginHistoryController',
        ]);
    
        Route::name('setting.')->prefix('setting')->group(function(){
    
            Route::name('index')->get('/','SettingController@index');
            Route::name('basic')->post('basic','SettingController@basic');
            Route::name('social')->post('social','SettingController@social');
            Route::name('payment')->post('payment','SettingController@payment');
            Route::name('icon')->post('icon','SettingController@icon');
            Route::name('slider')->post('slider','SettingController@slider');
    
        });
    
        Route::name('ajax.')->prefix('ajax')->group(function(){
            
            Route::name('delete_slider')->get('delete_slider/{id}', 'AjaxController@delete_slider');    
            Route::name('delete_photo')->get('delete_photo/{id}', 'AjaxController@delete_photo');    
            
        });
    
    });

});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }
}

resources/views/dashboard/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{{ getSetting('title') }} | {{ $title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="Admindek Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs." />
    <meta name="keywords" content="flat ui, admin Admin , Responsive, Landing, Bootstrap, App, Template, Mobile, iOS, Android, apple, creative app">
    <meta name="author" content="colorlib" />
	<meta name="csrf-token" content="{{ csrf_token() }}">
    @include('dashboard.layouts.css_general')
    {{ $custom_css }}
</head>

<body>
    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
        <div class="loader-bar"></div>
    </div>
    <!-- [ Pre-loader ] end -->
    <div id="pcoded" class="pcoded">
        <div class="pcoded-overlay-box"></div>
        <div class="pcoded-container navbar-wrapper">
            <!-- [ Header ] start -->
            @include('dashboard.layouts.header')

            <div class="pcoded-main-container">
                <div class="pcoded-wrapper">
                    @include('dashboard.layouts.sidebar')
                    <div class="pcoded-content">
                        {{ $content }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('dashboard.layouts.js_general')
    {{ $custom_js }}
    @include('alert')
</body>

</html>

resources/views/dashboard/layouts/css_general.blade.php
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand:500,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito">
    <link rel="stylesheet" href="{{ asset('themes/admindek/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('themes/admindek/css/waves.min.css') }}">
    <link rel="stylesheet" href="{{ asset('themes/admindek/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('themes/admindek/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('themes/admindek/css/widget.css') }}">
    <link rel="stylesheet" href="{{ asset('css/sweetalert2.css') }}">
    <link rel="stylesheet" href="{{ asset('css/custom.css?id=' . str_random(5)) }}">

resources/views/dashboard/layouts/header.blade.php
<nav class="navbar header-navbar pcoded-header">
    <div class="navbar-wrapper">
        <div class="navbar-logo">
            <a href="{{ route('dashboard') }}">
                <!-- <img class="img-fluid" src="{{ asset('themes/admindek/assets/icons/logo.png') }}" alt="Theme-Logo" /> -->
                Tiara_TV
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="#!">
                <i class="fa fa-menu icon-toggle-right"></i>
            </a>
            <a class="mobile-options waves-effect waves-light">
                <i class="fa fa-more-horizontal"></i>
            </a>
        </div>
        <div class="navbar-container container-fluid">
            <ul class="nav-right">
                <li class="user-profile header-notification">
                    <div class="dropdown-primary dropdown">
                        <div class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{ auth()->user()->image }}" class="img-radius" alt="User-Profile-Image">
                            <span>{{ auth()->user()->fullname }}</span>
                            <i class="fa fa-chevron-down"></i>
                        </div>
                        <ul class="show-notification profile-notification dropdown-menu" data-dropdown-in="fadeIn"
                            data-dropdown-out="fadeOut">
                            <li>
                                <a href="#">
                                    <i class="fa fa-wrench"></i> Settings
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-user-circle"></i> Profile
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('logout') }}">
                                    <i class="fa fa-sign-out-alt"></i> Sign Out
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/dashboard/layouts/js_general.blade.php
    <script src="{{ asset('themes/admindek/js/jquery.min.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/popper.min.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/waves.min.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/jquery.slimscroll.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/jquery.flot.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/jquery.flot.categories.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/curvedLines.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/jquery.flot.tooltip.min.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/chartist.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/amcharts.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/serial.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/light.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/pcoded.min.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/vertical-layout.min.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/custom-dashboard.min.js') }}"></script>
    <script src="{{ asset('themes/admindek/js/script.min.js') }}"></script>

resources/views/dashboard/layouts/sidebar.blade.php
<nav class="pcoded-navbar">
    <div class="nav-list">
        <div class="pcoded-inner-navbar main-menu">
            <div class="pcoded-navigation-label">Main</div>
            <ul class="pcoded-item pcoded-left-item">
                <li class="{{ active('dashboard') }}">
                    <a href="{{ route('dashboard') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-home"></i>
                        </span>
                        <span class="pcoded-mtext">Dashboard</span>
                    </a>
                </li>
                <li class="{{ active('order.*') }}">
                    <a href="{{ route('order.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fas fa-shopping-basket"></i>
                        </span>
                        <span class="pcoded-mtext">Orders</span>
                    </a>
                </li>
                <li class="{{ active('product.*') }}">
                    <a href="{{ route('product.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fas fa-tags"></i>
                        </span>
                        <span class="pcoded-mtext">Products</span>
                    </a>
                </li>
                <li class="{{ active('video.*') }}">
                    <a href="{{ route('video.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fab fa-youtube"></i>
                        </span>
                        <span class="pcoded-mtext">Video</span>
                    </a>
                </li>
            </ul>
            <div class="pcoded-navigation-label">Settings</div>
            <ul class="pcoded-item pcoded-left-item">
                <li class="{{ active('category.*') }}">
                    <a href="{{ route('category.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fas fa-th-large"></i>
                        </span>
                        <span class="pcoded-mtext">Manage Category</span>
                    </a>
                </li>
                <li class="{{ active('subcategory.*') }}">
                    <a href="{{ route('subcategory.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fas fa-th"></i>
                        </span>
                        <span class="pcoded-mtext">Manage Sub-Category</span>
                    </a>
                </li>
                <li class="{{ active('user.*') }}">
                    <a href="{{ route('user.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-users"></i>
                        </span>
                        <span class="pcoded-mtext">Manage Users</span>
                    </a>
                </li>
                <li class="{{ active('role.*') }}">
                    <a href="{{ route('role.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-user-tag"></i>
                        </span>
                        <span class="pcoded-mtext">Manage Roles</span>
                    </a>
                </li>
                <li class="{{ active('setting.*') }}">
                    <a href="{{ route('setting.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-wrench"></i>
                        </span>
                        <span class="pcoded-mtext">Settings</span>
                    </a>
                </li>
            </ul>
            <div class="pcoded-navigation-label"></div>
            <ul class="pcoded-item pcoded-left-item">
                <li class="{{ active('activity') }}">
                    <a href="{{ route('activity') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-th-list"></i>
                        </span>
                        <span class="pcoded-mtext">Activity History</span>
                    </a>
                </li>
                <li class="{{ active('login_history.*') }}">
                    <a href="{{ route('login_history.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-user-clock"></i>
                        </span>
                        <span class="pcoded-mtext">Login History</span>
                    </a>
                </li>
                <li class="">
                    <a href="{{ route('logout') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-sign-out-alt"></i>
                        </span>
                        <span class="pcoded-mtext">Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>